/**
 * scrape.js
 *
 * Use Playwright + system Chrome to scrape front-end job listings from multiple platforms.
 * Currently supports: 前程无忧 (51job), 拉勾网 (Lagou).
 *
 * Strategy: navigate to each search page and intercept API responses via
 * page.on('response') — this ensures real cookies and browser fingerprints.
 *
 * Lagou requires saved browser state (run `node scripts/lagou-login.js` first).
 *
 * Usage: node scripts/scrape.js
 */

'use strict';

const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const CHROME_PATH = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const KEYWORD = '前端';
const PAGES = 15;
const LAGOU_PAGES = 10;
const DELAY_MS = 2000;
const OUTPUT_DIR = path.resolve(__dirname, '..');

// Storage state file for lagou (generated by lagou-login.js)
const LAGOU_STATE_FILE = path.resolve(__dirname, '..', 'lagou-state.json');

// Output file paths
const OUTPUT_51JOB  = path.join(OUTPUT_DIR, 'raw_jobs_51job.json');
const OUTPUT_LAGOU  = path.join(OUTPUT_DIR, 'raw_jobs_lagou.json');
const OUTPUT_COMPAT = path.join(OUTPUT_DIR, 'raw_jobs.json'); // backward compat for analyze.js

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

/**
 * Check if lagou storage state file exists.
 */
function hasLagouState() {
  return fs.existsSync(LAGOU_STATE_FILE);
}

// ---------------------------------------------------------------------------
// 51job field extractor
// ---------------------------------------------------------------------------
function extractFields(item) {
  return {
    jobName:             item.jobName        ?? item.job_name         ?? '',
    jobId:               item.jobid          ?? item.jobId            ?? '',
    companyName:         item.companyName    ?? item.company_name     ?? '',
    jobAreaString:       item.jobAreaString  ?? item.job_area_sub     ?? '',
    provideSalaryString: item.provideSalaryString ?? item.providesalary_text ?? '',
    workYearString:      item.workYearString ?? item.workyear         ?? '',
    degreeString:        item.degreeString   ?? item.degreefrom       ?? '',
    jobTags:             Array.isArray(item.jobTags)      ? item.jobTags
                       : Array.isArray(item.jobwelf_list) ? item.jobwelf_list
                       : [],
    jobDescribe:         item.jobDescribe    ?? (Array.isArray(item.attribute_text)
                           ? item.attribute_text.join(' ') : item.attribute_text) ?? '',
    updateDate:          item.updateDate     ?? item.issuedate        ?? '',
  };
}

// ---------------------------------------------------------------------------
// 拉勾网 field extractor
// ---------------------------------------------------------------------------
function extractLagouFields(item) {
  return {
    jobName:             item.positionName || item.jobName || '',
    jobId:               String(item.positionId || item.id || ''),
    companyName:         item.companyName || item.company?.companyName || '',
    jobAreaString:       item.city || item.district || '',
    provideSalaryString: item.salary || item.salaryText || '',
    workYearString:      item.workYear || item.experience || '',
    degreeString:        item.education || item.degree || '',
    jobTags:             Array.isArray(item.skillLables) ? item.skillLables
                       : Array.isArray(item.label)       ? item.label
                       : [],
    jobDescribe:         item.positionAdvantage || item.jobDescription || '',
    updateDate:          item.createTime || item.refreshTime || '',
  };
}

// ---------------------------------------------------------------------------
// 从拉勾网 JSON 响应中尝试提取岗位列表
// ---------------------------------------------------------------------------
function extractLagouJobList(json) {
  const candidates = [
    json?.content?.positionResult?.result,
    json?.data?.result,
    json?.result?.pageItems,
  ];
  for (const list of candidates) {
    if (Array.isArray(list) && list.length > 0) return list;
  }
  return [];
}

// ---------------------------------------------------------------------------
// 前程无忧爬虫
// ---------------------------------------------------------------------------
async function scrape51job(context, pages) {
  console.log('\n[前程无忧] 开始采集...');
  const allJobs = [];
  const capturedResponses = [];

  const onResponse = async (response) => {
    const url = response.url();
    if (url.includes('we.51job.com/api/job/search-pc') || url.includes('search-pc')) {
      try {
        const json = await response.json();
        capturedResponses.push(json);
      } catch {
        // 忽略非 JSON 响应
      }
    }
  };
  context.on('response', onResponse);

  const page = await context.newPage();
  const searchUrl = `https://we.51job.com/pc/search?keyword=${encodeURIComponent(KEYWORD)}&searchType=2&sortType=0&metro=`;
  console.log(`[前程无忧] 打开搜索页: ${searchUrl}`);

  try {
    await page.goto(searchUrl, { waitUntil: 'networkidle', timeout: 60000 });
    await sleep(3000);

    console.log(`[前程无忧] 第 1 页已加载，捕获到 ${capturedResponses.length} 个 API 响应`);

    for (const json of capturedResponses.splice(0)) {
      const jobList = json?.engine_search_result?.job_list
                   ?? json?.resultbody?.job?.items
                   ?? [];
      const jobs = jobList.map(extractFields);
      allJobs.push(...jobs);
      if (jobs.length) console.log(`  [前程无忧] 第 1 页: ${jobs.length} 条岗位`);
    }

    for (let pageNo = 2; pageNo <= pages; pageNo++) {
      await sleep(DELAY_MS);

      try {
        const nextBtn = page.locator('button.next-page, a.next-page, [class*="next"], span:has-text("下一页"), button:has-text("下一页")').first();
        const visible = await nextBtn.isVisible({ timeout: 5000 }).catch(() => false);
        if (!visible) {
          console.log(`[前程无忧] 第 ${pageNo} 页：找不到下一页按钮，停止翻页`);
          break;
        }
        await nextBtn.click();
        await page.waitForLoadState('networkidle', { timeout: 15000 });
        await sleep(2000);
      } catch (err) {
        console.error(`[前程无忧] 翻页到第 ${pageNo} 页失败:`, err.message);
        break;
      }

      console.log(`[前程无忧] 第 ${pageNo} 页已加载，捕获到 ${capturedResponses.length} 个新响应`);

      for (const json of capturedResponses.splice(0)) {
        const jobList = json?.engine_search_result?.job_list
                     ?? json?.resultbody?.job?.items
                     ?? [];
        const jobs = jobList.map(extractFields);
        allJobs.push(...jobs);
        if (jobs.length) console.log(`  [前程无忧] 第 ${pageNo} 页: ${jobs.length} 条岗位`);
      }

      if (allJobs.length === 0 && pageNo >= 2) {
        console.log('[前程无忧] 连续无数据，停止');
        break;
      }
    }
  } finally {
    await page.close();
    context.off('response', onResponse);
  }

  console.log(`[前程无忧] 采集完成，共 ${allJobs.length} 条`);
  return { jobs: allJobs, platform: '前程无忧' };
}

// ---------------------------------------------------------------------------
// 拉勾网爬虫
// ---------------------------------------------------------------------------
async function scrapeLagou(context, pages) {
  console.log('\n[拉勾网] 开始采集...');
  const allJobs = [];
  const capturedResponses = [];

  const onResponse = async (response) => {
    const url = response.url();
    if (!url.includes('lagou.com')) return;
    try {
      const json = await response.json();
      capturedResponses.push(json);
    } catch {
      // 忽略非 JSON 响应
    }
  };
  context.on('response', onResponse);

  const page = await context.newPage();
  const searchUrl = `https://www.lagou.com/wn/jobs?fromSearch=true&kd=${encodeURIComponent(KEYWORD)}`;
  console.log(`[拉勾网] 打开搜索页: ${searchUrl}`);

  try {
    await page.goto(searchUrl, { waitUntil: 'networkidle', timeout: 60000 });
    await sleep(3000);

    console.log(`[拉勾网] 第 1 页已加载，捕获到 ${capturedResponses.length} 个响应`);

    for (const json of capturedResponses.splice(0)) {
      const jobList = extractLagouJobList(json);
      if (jobList.length > 0) {
        const jobs = jobList.map(extractLagouFields);
        allJobs.push(...jobs);
        console.log(`  [拉勾网] 第 1 页: ${jobs.length} 条岗位`);
      }
    }

    for (let pageNo = 2; pageNo <= pages; pageNo++) {
      await sleep(DELAY_MS);

      try {
        const nextBtn = page.locator([
          'button[class*="next"]',
          'a[class*="next"]',
          'button:has-text("下一页")',
          'a:has-text("下一页")',
          'span:has-text("下一页")',
        ].join(', ')).first();

        const visible = await nextBtn.isVisible({ timeout: 5000 }).catch(() => false);
        if (!visible) {
          console.log(`[拉勾网] 第 ${pageNo} 页：找不到下一页按钮，停止翻页`);
          break;
        }
        await nextBtn.click();
        await page.waitForLoadState('networkidle', { timeout: 15000 });
        await sleep(2000);
      } catch (err) {
        console.error(`[拉勾网] 翻页到第 ${pageNo} 页失败:`, err.message);
        break;
      }

      console.log(`[拉勾网] 第 ${pageNo} 页已加载，捕获到 ${capturedResponses.length} 个新响应`);

      for (const json of capturedResponses.splice(0)) {
        const jobList = extractLagouJobList(json);
        if (jobList.length > 0) {
          const jobs = jobList.map(extractLagouFields);
          allJobs.push(...jobs);
          console.log(`  [拉勾网] 第 ${pageNo} 页: ${jobs.length} 条岗位`);
        }
      }
    }
  } finally {
    await page.close();
    context.off('response', onResponse);
  }

  console.log(`[拉勾网] 采集完成，共 ${allJobs.length} 条`);
  return { jobs: allJobs, platform: '拉勾网' };
}

// ---------------------------------------------------------------------------
// 写入 JSON 文件
// ---------------------------------------------------------------------------
function writeJson(filePath, data) {
  if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`输出: ${filePath} (${data.length} 条)`);
}

// ---------------------------------------------------------------------------
// 主函数
// ---------------------------------------------------------------------------
async function main() {
  console.log('Launching browser...');

  let browser;
  try {
    browser = await chromium.launch({
      executablePath: CHROME_PATH,
      headless: false,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--window-size=1280,800'],
    });
  } catch {
    browser = await chromium.launch({ channel: 'chrome', headless: false });
  }

  // Shared browser options
  const contextOptions = {
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    viewport: { width: 1280, height: 800 },
    locale: 'zh-CN',
  };

  // --- 前程无忧 (普通 context) ---
  const ctx51job = await browser.newContext(contextOptions);
  let jobs51job = [];
  try {
    const result = await scrape51job(ctx51job, PAGES);
    jobs51job = result.jobs;
  } catch (err) {
    console.warn('[前程无忧] 采集失败，跳过:', err.message);
  }
  await ctx51job.close();

  // --- 拉勾网 (独立 context，带 storageState) ---
  let jobsLagou = [];
  if (hasLagouState()) {
    const ctxLagou = await browser.newContext({
      ...contextOptions,
      storageState: LAGOU_STATE_FILE,
    });
    console.log(`[拉勾网] 已加载浏览器状态: ${LAGOU_STATE_FILE}`);
    try {
      const result = await scrapeLagou(ctxLagou, LAGOU_PAGES);
      jobsLagou = result.jobs;
    } catch (err) {
      console.warn('[拉勾网] 采集失败，跳过:', err.message);
    }
    await ctxLagou.close();
  } else {
    console.warn('[拉勾网] 未找到 lagou-state.json，跳过采集');
    console.warn('         请先运行: node scripts/lagou-login.js');
  }

  await browser.close();

  // --- 写入文件 ---
  console.log('\n写入输出文件...');
  writeJson(OUTPUT_51JOB,  jobs51job);
  writeJson(OUTPUT_LAGOU,  jobsLagou);
  writeJson(OUTPUT_COMPAT, jobs51job); // backward compat: raw_jobs.json = 51job 数据

  console.log(`\n完成！`);
  console.log(`  前程无忧: ${jobs51job.length} 条`);
  console.log(`  拉勾网:   ${jobsLagou.length} 条`);
  console.log(`  合计:     ${jobs51job.length + jobsLagou.length} 条`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
